### ISSUE TITLE
Uuid not set when using custom entityClass

### ISSUE THREAD

**Issue by alexvanniel** [josbeir/cakephp-filesystem#11]
Again, I might be doing something wrong, or maybe I am just not understanding the procedure. However, I created my own Entity class (well, it actually already existed so I adapted it to fit with the plugin). 

When I do not use the custom Entity class, the resulting entity after uploading contains things like uuid, filename, size (not filesize even though this is mentioned in the documents), hash, meta, etc etc.

When I use my custom Entity class, the fields 'path', 'filename', 'size', 'mime', and 'hash' are set. The properties 'uuid', 'meta' and 'created' are not set however. I have added these properties to the $_accesible property of the Entity class, and I have set them to true for those fields. The Entity class is extends Entity and implements FileEntityInterface

Am I doing something wrong? Missing something? Understanding it wrong?

It might actually be intended behavior so CakePHP can generate Created and Uuid?

**Comment by josbeir** [comment]
If you are planning to store your file entities in a db row than its better to implement the FileEntityInterface instead of extending the FileEntity as that class is used to store your file in another way, for instance as a json string in a db field or as nested/primary elasticsearch record, ...

See https://github.com/josbeir/cakephp-filesystem#using-your-own-entities

* Cake will automatically generate a UUID string as ID if your primary key field has a length of 32 chars.
* Creation dates are also generated by cake if you enable the timestamp behavior on your table class..

So most things here are already there :-)

**Comment by alexvanniel** [comment]
Thanks. I did implement the interface, I think I was just expecting different things.
