### ISSUE TITLE
Cake 4.4.5 - Passed file (unknown) does not contain a valid resource

### ISSUE THREAD

**Issue by bergwerkweb** [josbeir/cakephp-filesystem#14]
Hey there - we just started a new Project with CakePHP 4.4.5 and run into an issue uploading files. (Running PHP 7.4 or 8.0 makes no difference). Our configuration (Local Filesystem) is identical to many other old projects.

The Error occurs when trying to upload a file:

`		$image = $this->request->getData($name);				
                $file = $this->getFilesystem('default')->upload($image,[
					'formatter' => 'Entity',
                    'data' => $entity,
                ]);
`

**Passed file (unknown) does not contain a valid resource**
Josbeir\Filesystem\Exception\FilesystemException
/vendor/josbeir/cakephp-filesystem/src/FileSourceNormalizer.php:78

Investigating further this issue can be traced to the namespace of the "UploadedFile" Class - CakePHP uses _Laminas\Diactoros\UploadedFile_ and cakephp-filesystem uses _Zend\Diactoros\UploadedFile_ and so the check in FileSourceNormalizer.php:65 (_instanceof UploadedFile_) seems to fail?

Is this a known issue and is there a simple solution for that?

**Comment by bergwerkweb** [comment]
We figured it out:

1. Use the alpha version: composer require josbeir/cakephp-filesystem "3.0-alpha.2"
2. change the default adapter to: 'adapter' => 'League\Flysystem\Local\LocalFilesystemAdapter'

**Comment by alexvanniel** [comment]
Isn't there a better way to do this? I mean, some packages might break because of the move to 3.0-alpha-2 since it requires 2.0 or 3.0 version of flysystem and I am not entirely sure if all the packages I am currently using support the 2.0 or 3.0 version of flysystem. Surely there is a fix to be found/done?

Also, this was not a problem before. CakePHP used to use the Laminas namespaced version of the UploadedFile and this plugin would also use the Zend namespaced UploadedFile. So somewhere in the Laminas package something must have changed breaking this check.
