### ISSUE TITLE
Release 3.0.2

### ISSUE THREAD

**Issue by Modicrumb** [josbeir/cakephp-filesystem#15]
Any updates on this? I know it's been a while since the repo has been touched. I realize this is prob not the best way to ask about this (by creating an issue) but not sure how else I would. In the latest cake unless this is released I can't use this plugin and I've been happy using it so far.

**Comment by alexvanniel** [comment]
Are you also running into the same problem as I am where uploading files is broken in the 2.0.1 version of the plugin?

**Comment by josbeir** [comment]
Sorry for the late reply guys.

As the 3.x version didn't get a stable release and the mixed composer dependency was causing some issues i decided to release version 3.0.2 as a Flysystem 3/PHP8.0+ only version.

Hope this solves any problems you guys are having.

**Comment by josbeir** [comment]
@Modicrumb  if you want a stable version of the previous alpha, i can release that version as 3.0.1 too...

**Comment by alexvanniel** [comment]
@josbeir Could you maybe create a separate branch for the 2.x release?? The only thing that is keeping me from using the 2.x release with the new CakePHP 4.4.6 release is the usage of the Zend namespace for UploadedFile. I forked yours, created a separate branch from commit 8e641f8efcba2441cde67a80939a8ff13acfa1ec and replaced the Zend namespace for Laminas. That fixed the issues without having to migrate to flysystem 3.0 Since there is a package that uses flysystem 1.x . I will be moving to the new flysystem but I need to upgrade the other package first and that takes time. Not sure if you can help me with this.

**Comment by josbeir** [comment]
@alexvanniel  done!

**Comment by alexvanniel** [comment]
@josbeir  Great stuff! Thanks, I did a pull request on the branch 2.x branch. Would it then also be an option that that would become release 2.0.2 or something and that it could be available on packagist? I might be pushing here but this would really help me out.

**Comment by josbeir** [comment]
@alexvanniel  done! Unit testing seems to pass so i'm hoping all is good :-)

**Comment by alexvanniel** [comment]
@josbeir I don't really expect any weird issues, seeing the Laminas\Diactoros\UploadedFile used to be an instance of the Zend version (I think, but I haven't been able to proof this as of yet). Here's hoping all goes well and waiting for the packagist package then, I guess.

**Comment by josbeir** [comment]
@alexvanniel I did a force update on packagist. enjoy!

**Comment by alexvanniel** [comment]
@josbeir Legend! Thanks so much.
